### PR TITLE
Reintroduce missed properties for erlang_types

### LINKED ISSUE #16: AttributeError: 'String' object has no attribute 'value'
I see it since the fix of #14 (I use `0.6.0` version with the fix) and I see newly:

```
In [5]: BeamFile('/tmp/usr/lib/erlang/m.beam').compileinfo['source'].value                                                                                                                                                                                                      
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-ecdd9a5ca3fa> in <module>
----> 1 BeamFile('/tmp/usr/lib/erlang/m.beam').compileinfo['source'].value

AttributeError: 'String' object has no attribute 'value'
```

this used to work with `0.6.0`.

### PR DESCRIPTION
**Pull request by matwey**
Fix #16 

Fixes: b1dbf0f ("Refactor erlang_types using collections.namedtuple")

### CODE REVIEW

**Comment by matwey** [comment]
@marxin could you try if `x.value` works for you again?

**Comment by marxin** [comment]
Yes, I can confirm that. Thanks.
