### ISSUE TITLE
AttributeError: 'String' object has no attribute 'value'

### ISSUE THREAD

**Issue by marxin** [matwey/pybeam#16]
I see it since the fix of #14 (I use `0.6.0` version with the fix) and I see newly:

```
In [5]: BeamFile('/tmp/usr/lib/erlang/m.beam').compileinfo['source'].value                                                                                                                                                                                                      
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-ecdd9a5ca3fa> in <module>
----> 1 BeamFile('/tmp/usr/lib/erlang/m.beam').compileinfo['source'].value

AttributeError: 'String' object has no attribute 'value'
```

this used to work with `0.6.0`.

**Comment by matwey** [comment]
Yes, sorry. I've break the interface. I'll just put the `.value` back for compatibility.

**Comment by marxin** [comment]
Thanks.
